version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=bed_booked
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ../bed-booker-front/
    ports:
      - "4200:80"
    depends_on:
      - backend
